# Generated by Django 2.2.3 on 2019-07-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='corr_ans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Correct',
        ),
        migrations.AddField(
            model_name='question',
            name='track_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Polls.Track'),
        ),
    ]
