# Generated by Django 2.2.3 on 2019-07-31 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0002_auto_20190731_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='track_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Polls.Track'),
        ),
    ]
