# Generated by Django 2.2.3 on 2019-07-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0004_remove_choice_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='track_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Polls.Track'),
        ),
    ]
