# Generated by Django 2.2.3 on 2019-07-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0006_remove_choice_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='track_id',
            new_name='track',
        ),
    ]
